# Generated by Django 5.0.3 on 2024-05-02 05:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerceapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Contect',
            new_name='Contact',
        ),
    ]
